-- ============================================================
-- Vitrine CMV — esquema completo do Supabase
-- ------------------------------------------------------------
-- Como usar:
--   1. Abra https://supabase.com e entre no seu projeto
--   2. Menu lateral: "SQL Editor"  ->  "New query"
--   3. Cole TODO este conteudo e clique em "Run"
--
-- E seguro: NAO apaga nenhum dado. So cria tabelas/colunas que
-- estiverem faltando e libera as permissoes de leitura/escrita.
-- Pode rodar quantas vezes quiser.
-- ============================================================

-- ---------- PRODUTOS ----------
create table if not exists produtos (id bigint primary key);
alter table produtos add column if not exists nome text;
alter table produtos add column if not exists curva text;
alter table produtos add column if not exists validade integer;
alter table produtos add column if not exists categoria text;
alter table produtos add column if not exists vitrine text;
alter table produtos add column if not exists custo numeric;
alter table produtos add column if not exists preco numeric;
alter table produtos add column if not exists resp text;
alter table produtos add column if not exists unidade text;
alter table produtos add column if not exists obs text;
alter table produtos add column if not exists tipo text;
alter table produtos add column if not exists qtd_comprada numeric;
alter table produtos add column if not exists valor_compra numeric;
alter table produtos add column if not exists preco_unidade text;
alter table produtos add column if not exists encomenda boolean;

-- ---------- PRODUTO_COMPRAS (historico de revenda) ----------
create table if not exists produto_compras (id bigint primary key);
alter table produto_compras add column if not exists prod_id bigint;
alter table produto_compras add column if not exists fornecedor text;
alter table produto_compras add column if not exists data date;
alter table produto_compras add column if not exists qtd_compra numeric;
alter table produto_compras add column if not exists custo_compra numeric;
alter table produto_compras add column if not exists created_at timestamptz default now();

-- ---------- CATEGORIAS ----------
create table if not exists categorias (id bigint generated by default as identity primary key);
alter table categorias add column if not exists nome text;

-- ---------- VITRINE_TIPOS ----------
create table if not exists vitrine_tipos (id text primary key);
alter table vitrine_tipos add column if not exists nome text;

-- ---------- INGREDIENTES ----------
create table if not exists ingredientes (id bigint primary key);
alter table ingredientes add column if not exists nome text;
alter table ingredientes add column if not exists unidade text;
alter table ingredientes add column if not exists qtd_compra numeric;
alter table ingredientes add column if not exists custo_compra numeric;
alter table ingredientes add column if not exists fatia numeric;
alter table ingredientes add column if not exists variacao_unidade text;

-- ---------- RECEITAS (fichas tecnicas) ----------
create table if not exists receitas (id bigint primary key);
alter table receitas add column if not exists prod_id bigint;
alter table receitas add column if not exists rendimento numeric;
alter table receitas add column if not exists unidade text;
alter table receitas add column if not exists peso_por_unidade numeric;
alter table receitas add column if not exists created_at timestamptz default now();

-- ---------- RECEITA_ITENS (ingredientes de cada ficha) ----------
create table if not exists receita_itens (id bigint generated by default as identity primary key);
alter table receita_itens add column if not exists receita_id bigint;
alter table receita_itens add column if not exists ing_id bigint;
alter table receita_itens add column if not exists qtd numeric;

-- ---------- PERDAS ----------
create table if not exists perdas (id bigint primary key);
alter table perdas add column if not exists unit text;
alter table perdas add column if not exists prod_id bigint;
alter table perdas add column if not exists qty numeric;
alter table perdas add column if not exists tipo text;
alter table perdas add column if not exists data date;
alter table perdas add column if not exists obs text;
alter table perdas add column if not exists source text;

-- ---------- VITRINE_SLOTS ----------
create table if not exists vitrine_slots (id bigint generated by default as identity primary key);
alter table vitrine_slots add column if not exists unit text;
alter table vitrine_slots add column if not exists dia text;
alter table vitrine_slots add column if not exists slot text;
alter table vitrine_slots add column if not exists prod_id bigint;
alter table vitrine_slots add column if not exists qty numeric;
alter table vitrine_slots add column if not exists produced_qty numeric;
alter table vitrine_slots add column if not exists entry_at timestamptz;
alter table vitrine_slots add column if not exists status text;

-- ---------- CRONOGRAMA ----------
create table if not exists cronograma (id bigint generated by default as identity primary key);
alter table cronograma add column if not exists unit text;
alter table cronograma add column if not exists dia text;
alter table cronograma add column if not exists hora time;
alter table cronograma add column if not exists tarefa text;
alter table cronograma add column if not exists resp text;
alter table cronograma add column if not exists prod_id bigint;
alter table cronograma add column if not exists qty numeric;

-- ---------- APOIO_PRODUCAO ----------
create table if not exists apoio_producao (id bigint generated by default as identity primary key);
alter table apoio_producao add column if not exists unit text;
alter table apoio_producao add column if not exists dia text;
alter table apoio_producao add column if not exists prod_id bigint;
alter table apoio_producao add column if not exists nome text;
alter table apoio_producao add column if not exists qty numeric;
alter table apoio_producao add column if not exists created_at timestamptz default now();

-- ---------- PLANO_SEMANAL ----------
create table if not exists plano_semanal (id bigint generated by default as identity primary key);
alter table plano_semanal add column if not exists unit text;
alter table plano_semanal add column if not exists dia text;
alter table plano_semanal add column if not exists prod_id bigint;
alter table plano_semanal add column if not exists qty numeric;

-- ---------- FECHAMENTOS ----------
create table if not exists fechamentos (id bigint generated by default as identity primary key);
alter table fechamentos add column if not exists unit text;
alter table fechamentos add column if not exists dia text;
alter table fechamentos add column if not exists data_fechamento date;
alter table fechamentos add column if not exists prod_id bigint;
alter table fechamentos add column if not exists slot text;
alter table fechamentos add column if not exists planned_qty numeric;
alter table fechamentos add column if not exists produced_qty numeric;
alter table fechamentos add column if not exists entry_at timestamptz;
alter table fechamentos add column if not exists status text;
alter table fechamentos add column if not exists leftover_qty numeric;

-- ============================================================
-- PERMISSOES (RLS) — libera leitura e escrita com a chave publica
-- ============================================================
do $$
declare t text;
begin
  foreach t in array array[
    'produtos','produto_compras','categorias','vitrine_tipos','ingredientes',
    'receitas','receita_itens','perdas','vitrine_slots','cronograma',
    'apoio_producao','plano_semanal','fechamentos'
  ] loop
    execute format('alter table %I enable row level security;', t);
    execute format('drop policy if exists ddv_all on %I;', t);
    execute format('create policy ddv_all on %I for all to anon, authenticated using (true) with check (true);', t);
  end loop;
end $$;
